#!/usr/bin/env python
#==============================================================================
#                      Start the Clair GUI
#==============================================================================
from clair.qtgui import GuiMain

GuiMain.application_main()
