# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('econdata', '0002_auto_20170501_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Internal unique ID of each scheduled event.')),
                ('due_time', models.DateTimeField(verbose_name='Time when event should be executed.')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='econdata.Listing', verbose_name='The listing that should be updated.')),
            ],
        ),
        migrations.CreateModel(
            name='SearchTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Internal unique ID of each search task.')),
                ('recurrence', models.DurationField(verbose_name='How frequently should the task be executed.')),
                ('server', models.CharField(max_length=64, verbose_name='The server where products should be searched.')),
                ('query_string', models.CharField(blank=True, default='', max_length=128, verbose_name='The query string that is given to the server. If the string is blank, it is constructed from the product.')),
                ('n_listings', models.IntegerField(verbose_name='Number of listings that should be returned by the server.')),
                ('price_min', models.FloatField(blank=True, null=True, verbose_name='Minimum price for searched items.')),
                ('price_max', models.FloatField(blank=True, null=True, verbose_name='Maximum price for searched items.')),
                ('currency', models.CharField(blank=True, default='', max_length=3, verbose_name='Currency of the prices.')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_search_task', to='econdata.Product', verbose_name='The product which is searched by this task.')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='search_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collect.SearchTask', verbose_name='The search task that should be executed.'),
        ),
    ]
