# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_listingfoundby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingfoundby',
            name='listing',
            field=models.CharField(default=None, max_length=128, verbose_name='ID of the listing that was found by the task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingfoundby',
            name='task',
            field=models.IntegerField(default=None, verbose_name='ID of the task that found the listing'),
            preserve_default=False,
        ),
    ]
