# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20170519_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtask',
            name='server',
            field=models.CharField(choices=[('EBAY-AT', 'EBAY-AT'), ('EBAY-AU', 'EBAY-AU'), ('EBAY-CH', 'EBAY-CH'), ('EBAY-DE', 'EBAY-DE'), ('EBAY-ENC', 'EBAY-ENC'), ('EBAY-ES', 'EBAY-ES'), ('EBAY-FR', 'EBAY-FR'), ('EBAY-FRB', 'EBAY-FRB'), ('EBAY-FRC', 'EBAY-FRC'), ('EBAY-GB', 'EBAY-GB'), ('EBAY-HK', 'EBAY-HK'), ('EBAY-IE', 'EBAY-IE'), ('EBAY-IN', 'EBAY-IN'), ('EBAY-IT', 'EBAY-IT'), ('EBAY-MOT', 'EBAY-MOT'), ('EBAY-MY', 'EBAY-MY'), ('EBAY-NL', 'EBAY-NL'), ('EBAY-NLB', 'EBAY-NLB'), ('EBAY-PH', 'EBAY-PH'), ('EBAY-PL', 'EBAY-PL'), ('EBAY-SG', 'EBAY-SG'), ('EBAY-US', 'EBAY-US')], max_length=64, verbose_name='The server where products should be searched.'),
        ),
    ]
