#!/usr/bin/env python
# -*- coding: utf-8 -*-
#==============================================================================
#                      Start the Clair GUI
#==============================================================================
from clair.qtgui import GuiMain

GuiMain.application_main()
