# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Internal unique ID of each listing. Approximate pattern: date-site-id_site, for example: 2017-01-01-Ebay-123478901234567')),
                ('site', models.CharField(max_length=8, verbose_name="String to identify the remote site. For example 'Ebay'.")),
                ('id_site', models.CharField(max_length=44, verbose_name='ID of listing on the remote site.')),
                ('description', models.CharField(blank=True, default='', max_length=8192, verbose_name='Long description of listing.')),
                ('prod_spec', models.CharField(blank=True, default='', max_length=256, verbose_name="Product specific name value pairs (dict), in JSON. For example: ``{'megapixel': '12'}``. The ``ItemSpecifics`` on Ebay.")),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('new-defects', 'New with defects'), ('refurbished', 'Refurbished'), ('used', 'Used'), ('used-very-good', 'Used very good'), ('used-good', 'Used good'), ('used-acceptable', 'Used acceptable'), ('not-working', 'Not working')], default='', max_length=16, verbose_name='Condition of the sold item(s):')),
                ('time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Time when price is/was valid. End time in case of auctions.')),
                ('currency', models.CharField(blank=True, default='', max_length=3, verbose_name='Currency for price EUR, USD, ...')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Price of listing (all items together).')),
                ('shipping_price', models.FloatField(blank=True, default=None, null=True, verbose_name='Shipping cost')),
                ('is_real', models.NullBooleanField(default=None, verbose_name='If True: One could really buy the item for this price. This is not a temporary price from an ongoing auction.')),
                ('is_sold', models.NullBooleanField(default=None, verbose_name='Successful sale if ``True``.')),
                ('location', models.CharField(blank=True, default='', max_length=64, verbose_name='Location of item (pre sale)')),
                ('shipping_locations', models.CharField(blank=True, default='', max_length=64, verbose_name='Locations to where the item(s) can be shipped.')),
                ('seller', models.CharField(blank=True, default='', max_length=64, verbose_name='User name of seller.')),
                ('buyer', models.CharField(blank=True, default='', max_length=64, verbose_name='User name of buyer.')),
                ('item_url', models.CharField(blank=True, default='', max_length=256, verbose_name='Link to web representation of listing.')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('canceled', 'Canceled'), ('ended', 'Ended')], default='', max_length=8, verbose_name='State of the listing: active, canceled, ended')),
                ('listing_type', models.CharField(blank=True, choices=[('auction', 'Auction'), ('classified', 'Classified'), ('fixed-price', 'Fixed price')], default='', max_length=16, verbose_name='Type of the listing: auction, classified, fixed-price')),
            ],
        ),
    ]
