# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econdata', '0004_auto_20170520_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id_site',
            field=models.CharField(max_length=44, verbose_name="The listing's ID on the remote site."),
        ),
    ]
